imports:
    - { resource: parameters.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: false
    bundles:        [MayflowerJiraIssueVoteBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Jira Vote Configuration
mayflower_jira_issue_vote:
    consumer_key:    %jira_secret%
    consumer_secret: %private_key%
    oauth_host:      %jira_host%
    client_host:     http://jira-vote.dev

# Rest api configuration
fos_rest:
    body_listener:          true
    format_listener:        true
    param_fetcher_listener: true
    view:
        view_response_listener: force
        failed_validation:      HTTP_BAD_REQUEST
        default_engine:         twig
        formats:
            json:  true
    format_listener:
        rules:
            - { path: ^/api, priorities: [html, json], fallback_format: ~, prefer_extension: false }
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true

# Bower
sp_bower:
    bundles:
        MayflowerJiraIssueVoteBundle:
            json_file:  bower.json
            config_dir: Resources/config/bower
            asset_dir:  ../../public/vendor
            cache:      ../../bower_cache
    allow_root: true
    assetic:
        enabled: false
