services:
    mayflower_url_generator:
        class: Symfony\Component\Routing\Generator\UrlGenerator
        public: false
        factory: [@router, getGenerator]

    mayflower_oauth_credentials:
        class: Mayflower\JiraIssueVoteBundle\Jira\Credentials\JiraOAuthCredentials
        arguments:
            - "%consumer_key%"
            - "%consumer_secret%"

    mayflower_client_factory:
        class: Mayflower\JiraIssueVoteBundle\Jira\ClientFactory
        arguments:
            - @mayflower_oauth_credentials
            - %host%

    mayflower_token_fetcher:
        class: Mayflower\JiraIssueVoteBundle\Jira\TokenFetcher
        arguments:
            - @mayflower_url_generator
            - @mayflower_client_factory
            - %host%

    mayflower_rest_handler:
        class: Mayflower\JiraIssueVoteBundle\Jira\RestHandler
        arguments:
            - @session
            - @mayflower_client_factory
            - %host%

    mayflower_error_listener:
        class: Mayflower\JiraIssueVoteBundle\EventListener\OAuthCredentialsListener
        tags:
         - { name: kernel.event_subscriber }
