ma27_jira_issue_vote_homepage:
    path: /
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:index }

ma27_jira_issue_vote_verify:
    path: /unauthorized
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:index }

ma27_jira_issue_vote_verify_callback:
    path: /verifier/callback
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:callback }

ma27_jira_issue_vote_select_filter:
    path: /filter/select
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:selectFilter }

ma27_jira_issue_vote_voter:
    path: /vote-issue/{issue_id}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:vote, _method: POST }

ma27_jira_issue_vote_unvote:
    path: /unvote-issue/{issue_id}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:unvote, _method: DELETE }

ma27_jira_issue_vote_logout:
    path: /logout
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:invalidateTokens }
