mayflower_issues:
    path:    '/issue-data'
    methods:  ['GET']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:loadIssues, _format: json }

mayflower_filters:
    path:     '/source/{type}'
    methods:  ['GET']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:loadIssueSource, _format: json }

mayflower_select_filters:
    path:     '/source/{type}'
    methods:  ['POST']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:storeFavouriteFilter, _format: json }
