mayflower_issues:
    path:    '/issue-data'
    methods:  ['GET']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:loadIssues, _format: json }

mayflower_filters:
    path:     '/filters'
    methods:  ['GET']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:loadFilters, _format: json }

mayflower_select_filters:
    path:     '/filters'
    methods:  ['POST']
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Api:selectFilter, _format: json }
