ma27_jira_issue_vote_homepage:
    path: /
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:index }

ma27_jira_issue_vote_verify:
    path: /unauthorized
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:index }

ma27_jira_issue_vote_verify_callback:
    path: /verifier/callback
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:callback }

ma27_jira_issue_vote_select_filter:
    path: /filter/select
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:selectFilter }

ma27_jira_issue_vote_voter:
    path: /vote-issue/{issue_id}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:vote }

ma27_jira_issue_vote_unvote:
    path: /unvote-issue/{issue_id}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:unvote }

ma27_jira_issue_vote_logout:
    path: /logout
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Authorize:invalidateTokens }

ma27_jira_issue_vote_settings_hide_voted:
    path: /settings/voted/{option}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:setHideIssues }

ma27_jira_issue_vote_settings_hide_reported:
    path: /settings/reported/{option}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:setReportedIssues }

ma27_jira_issue_vote_settings_hide_resolved:
    path: /settings/resolved/{option}
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:setResolvedIssues }

ma27_jira_issue_vote_settings_list:
    path: /settings/list
    defaults: { _controller: MayflowerJiraIssueVoteBundle:Issue:settingsList }
