services:
    ma27_jira_issue_vote.client:
        class: Mayflower\JiraIssueVoteBundle\Util\JiraClient
        arguments: [%host%]

    ma27_jira_issue_vote.oauth_credential.url_generator:
        class: Mayflower\JiraIssueVoteBundle\Util\Generator\OAuthUrlGenerator
        arguments: [%host%, @router, %client%]

    ma27_jira_issue_vote.oauth.factory:
        class: Mayflower\JiraIssueVoteBundle\Util\OAuthPluginFactory
        arguments: [%consumer_key%, %consumer_secret%]

    ma27_jira_issue_vote.oauth.proxy:
        class: Mayflower\JiraIssueVoteBundle\Util\OAuthSecurityToken
        arguments: [@session]

    ma27_jira_issue_vote.oauth.provider:
        class: Mayflower\JiraIssueVoteBundle\Util\OAuthSecurityAccessProvider
        arguments: [@ma27_jira_issue_vote.client, @ma27_jira_issue_vote.oauth_credential.url_generator]

    ma27_jira_issue_vote.oauth.adapter:
        class: Mayflower\JiraIssueVoteBundle\Service\JiraPropertyAdapter
        arguments: [@ma27_jira_issue_vote.oauth.provider]

    ma27_jira_issue_vote.issue.manager:
        class: Mayflower\JiraIssueVoteBundle\Service\IssueDataViewContext
        arguments: [@ma27_jira_issue_vote.oauth.adapter]

    ma27_jira_issue_vote.filter.reported:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueReportedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.resolved:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueResolvedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.voted:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueVotedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.container:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\FilterContainer
        calls:
          - [set, ['@ma27_jira_issue_vote.filter.reported']]
          - [set, ['@ma27_jira_issue_vote.filter.resolved']]
          - [set, ['@ma27_jira_issue_vote.filter.voted']]

    ma27_jira_issue_vote.listener.jira_credentials:
        class: Mayflower\JiraIssueVoteBundle\EventListener\JiraCredentialsListener
        arguments: [@ma27_jira_issue_vote.oauth.proxy]
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: kernel.event_subscriber }
