services:
    ma27_jira_issue_vote.oauth.adapter:
        class: Mayflower\JiraIssueVoteBundle\Service\JiraPropertyAdapter
        arguments: [@mayflower_rest_handler]

    ma27_jira_issue_vote.issue.manager:
        class: Mayflower\JiraIssueVoteBundle\Service\IssueDataViewContext
        arguments: [@ma27_jira_issue_vote.oauth.adapter]

    ma27_jira_issue_vote.filter.reported:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueReportedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.resolved:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueResolvedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.voted:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\Iterator\IssueVotedIterator
        arguments: [@session]

    ma27_jira_issue_vote.filter.container:
        class: Mayflower\JiraIssueVoteBundle\Service\Filter\FilterContainer
        calls:
          - [set, ['@ma27_jira_issue_vote.filter.reported']]
          - [set, ['@ma27_jira_issue_vote.filter.resolved']]
          - [set, ['@ma27_jira_issue_vote.filter.voted']]
